import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/colors";

export const styles = StyleSheet.create({
  container:{
    paddingHorizontal:10,
  },
  inputContainer:{
    marginVertical:5
  },
  inputTitle:{
    fontFamily:"MartinMono-Bold",
    paddingBottom:5,
    color:COLORS.dark
  },
  photosContainer:{
    flexDirection:"row",
    justifyContent:"space-between",
  },
  photoContainer:{
    width:100,
    height:100,
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"gray",
    borderRadius:5
  },
  addPhoto:{
    fontFamily:"MartinMono-Light",
    fontSize:25,
  },
  photoDescription:{
    paddingTop:5,
    paddingBottom:15,
    fontFamily:"MartinMono-Light",
    fontSize:11,
  },
  input:{
    color:COLORS.dark,

  },
  genderContainer:{
    paddingHorizontal:1,
    flexDirection:"row",
    justifyContent:"space-between"
  },
  touchableGender:{
    width:"33%",
    height:100,
    alignItems:"center",
    justifyContent:"center",
    borderColor:COLORS.dark,
    borderWidth:.5,
    borderRadius:5,
  },
  appearanceContainer:{
    paddingHorizontal:1,
    flexDirection:"row",
  },
  touchableAppearance:{
    width:"50%",
    height:100,
    borderColor:COLORS.dark,
    borderWidth:.5,
    borderRadius:5,
    alignItems:"center",
    justifyContent:"center",

  },
  idContainer:{
    height:50,
    alignItems:"center",
    flexDirection:"row",
  },
  checkBox:{
    marginLeft:1,
    marginHorizontal:10,
  },
  checkIcon:{
    fontSize:25
  },
  idText:{
    fontFamily:"MartinMono-Light",
    fontSize:12,
  },
  lossZone:{
    height:100,
    borderWidth:1
  },
  publishBtnContainer:{
    backgroundColor:COLORS.primary,
    borderRadius:10,
    alignItems:"center",
    justifyContent:"center",
    padding:15,
    width:"82%",
    position:"absolute",
    bottom:10,
    left:"10%",
  },
  publishText:{
    fontFamily:"MartinMono-Bold",
    color:COLORS.white
  },
  bottom:{
    paddingBottom:50
  },
})