import { StyleSheet } from "react-native";

import { COLORS } from "../../constants/colors";

export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:COLORS.background,
  },
  imageContainer:{
    flex:1,
  },
  isLost:{
    position:"absolute",
    zIndex:100,
    bottom:10,
    left:10,
    backgroundColor:COLORS.dark,
    borderRadius:10,
    padding:5,
    fontFamily:"MartinMono-Regular",
    color:COLORS.danger,
    opacity:0.8,
    
  },
  image:{
    width:"100%",
    height:300
  },
  title:{
    color:COLORS.primary,
    fontFamily:"MartinMono-Bold",
    fontSize:25,
    padding:10
  },
  descriptionText:{
    fontFamily:"MartinMono-Regular",
    fontSize:15,
    paddingHorizontal:10,
    paddingBottom:30
  },
  detailContainer:{
    borderTopWidth:2,
    borderTopColor:COLORS.secondary,
    marginHorizontal:10
  },
  detailTitle:{
    paddingVertical:15,
    fontFamily:"MartinMono-Medium",
    fontSize:20
  },
  date:{
    borderTopWidth:2,
    borderTopColor:COLORS.secondary,
    fontFamily:"MartinMono-Light",
    fontSize:14,
    paddingTop:20
  },
  lossLocation:{
    fontFamily:"MartinMono-Light",
    fontSize:14,
    paddingVertical:5
  },
  contact:{
    padding:10,
    fontFamily:"MartinMono-Regular",
    fontSize:18,
    backgroundColor:COLORS.secondary,
    marginTop:5
  },
})