import { StyleSheet } from "react-native";

import { COLORS } from "../../constants/colors";

export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:COLORS.background
  },
  profileContainer:{
    backgroundColor:COLORS.primary,
    flex:.5,
  },
  profileDataContainer:{
    flexDirection:"row",
    alignItems:"center",
  },
  editContainer:{
    position:"absolute",
    top:20,
    right:20,
  },
  image:{
    width:100,
    height:100,
    borderRadius:50,
    marginHorizontal:22
  },
  profileIcon:{
    paddingHorizontal:22,
  },
  dataContainer:{
    height:"80%",
    justifyContent:"space-evenly",
  },
  name:{
    fontFamily:"MartinMono-Bold",
    color:COLORS.dark,
    fontSize:14,
  },
  email:{
    fontFamily:"MartinMono-Light",
    color:COLORS.dark,
    fontSize:11,
    alignSelf:"center",
  },
  optionsContainer:{
    flex:1
  },
  option:{
    paddingVertical:20,
    marginHorizontal:20,
    borderBottomWidth:1,
    borderColor:COLORS.details
  },
  optionText:{
    color:COLORS.dark,
    fontFamily:"MartinMono-Regular"
  },
  logoContainer:{
    width:"100%",
    position:"absolute",
    bottom:20,
    alignItems:"center",
    justifyContent:"center",
  },
  logo:{
    height:100,
    width:100,
  },
  logoName:{
    paddingBottom:5,
    fontFamily:"MartinMono-Regular",
    color:COLORS.primary
  },
  logoText:{
    fontFamily:"MartinMono-Regular",
    fontSize:9,
    color:COLORS.dark
  }
})